name: Close inactive issues
on:
  schedule:
    - cron: "30 8 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v3
        with:
          days-before-issue-close: 5
          close-issue-message: "This issue was automatically closed awaiting a response from the creator. Please re-open with more information."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-labels: need-feedback