name: PHPUnit

on:
    pull_request:
        branches: [master]
        paths:
                - '**/*.php'
                - '**/composer.lock'
                - '**/phpcs.xml'
                - '**/phpunit.xml.dist'
                - '**/psalm.xml'

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
                matrix:
                        php: [7.4]

    steps:
        - uses: actions/checkout@v2

        - name: Cache dependencies
            uses: actions/cache@v1
            with:
                    path: ~/.composer/cache/files
                    key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

        - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: ${{ matrix.php }}
                extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                coverage: none

        - name: Start MySQL
            run: sudo /etc/init.d/mysql start

        - name: Install dependencies
            run: composer update --prefer-dist --no-interaction --no-suggest

        - name: Setup tests
            run: bash bin/install-wp-tests.sh wordpress_test root root localhost latest

        - name: Working Directory
            run: pwd

        - name: Execute tests
            run: yarn test:php
            env:
                DB_PORT: ${{ job.services.mysql.ports[3306] }}
